version: '3.1'

services:
  db:
    image: postgres:13
    

    environment:
      POSTGRES_DB: wordpress
      POSTGRES_USER: wordpress
      POSTGRES_PASSWORD: Anudeep
      
      
      
    volumes:
      - db_data:/var/lib/postgresql/data

  wordpress:
    image: wordpress:php7.4-apache
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:5432
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      
      
      WORDPRESS_DB_PASSWORD: Anudeep
    volumes:
      - wordpress:/var/www/html

volumes:
  db_data:
  wordpress: